// Code generated by gocc; DO NOT EDIT.

package parser

import (
     "babyduck/semantic"
)
var functionDir = semantic.NewFunctionDirectory()
var cuadruple = semantic.NewCuadruploList(functionDir)

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib, interface{}) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Start	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Start : Program	<< functionDir, nil >>`,
		Id:         "Start",
		NTType:     1,
		Index:      1,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return functionDir, nil
		},
	},
	ProdTabEntry{
		String: `Program : program id semicolon VarsOp FuncLoop main Body end	<< cuadruple.PrintCuadruplosAction() >>`,
		Id:         "Program",
		NTType:     2,
		Index:      2,
		NumSymbols: 8,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.PrintCuadruplosAction()
		},
	},
	ProdTabEntry{
		String: `VarsOp : Vars	<<  >>`,
		Id:         "VarsOp",
		NTType:     3,
		Index:      3,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `VarsOp : empty	<<  >>`,
		Id:         "VarsOp",
		NTType:     3,
		Index:      4,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Vars : var Variable VarsPrime	<<  >>`,
		Id:         "Vars",
		NTType:     4,
		Index:      5,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Variable : AddVarId MasId colon Type semicolon	<< functionDir.SaveVariables(X[3].(semantic.Type)) >>`,
		Id:         "Variable",
		NTType:     5,
		Index:      6,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return functionDir.SaveVariables(X[3].(semantic.Type))
		},
	},
	ProdTabEntry{
		String: `MasId : comma AddVarId MasId	<<  >>`,
		Id:         "MasId",
		NTType:     6,
		Index:      7,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MasId : empty	<<  >>`,
		Id:         "MasId",
		NTType:     6,
		Index:      8,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `AddVarId : id	<< functionDir.AppendVariable(X[0]) >>`,
		Id:         "AddVarId",
		NTType:     7,
		Index:      9,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return functionDir.AppendVariable(X[0])
		},
	},
	ProdTabEntry{
		String: `VarsPrime : Variable	<<  >>`,
		Id:         "VarsPrime",
		NTType:     8,
		Index:      10,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `VarsPrime : empty	<<  >>`,
		Id:         "VarsPrime",
		NTType:     8,
		Index:      11,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `FuncLoop : Funcs FuncLoop	<<  >>`,
		Id:         "FuncLoop",
		NTType:     9,
		Index:      12,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FuncLoop : empty	<<  >>`,
		Id:         "FuncLoop",
		NTType:     9,
		Index:      13,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Funcs : RegisterFunc lparen Params rparen lbracket Vars Body rbracket semicolon	<<  >>`,
		Id:         "Funcs",
		NTType:     10,
		Index:      14,
		NumSymbols: 9,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `RegisterFunc : void id	<< functionDir.RegisterFunction(X[1], semantic.Void) >>`,
		Id:         "RegisterFunc",
		NTType:     11,
		Index:      15,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return functionDir.RegisterFunction(X[1], semantic.Void)
		},
	},
	ProdTabEntry{
		String: `Params : ParamIndiv MoreParam	<<  >>`,
		Id:         "Params",
		NTType:     12,
		Index:      16,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Params : empty	<<  >>`,
		Id:         "Params",
		NTType:     12,
		Index:      17,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `ParamIndiv : id colon Type	<< functionDir.RegisterParam(X[0], X[2].(semantic.Type)) >>`,
		Id:         "ParamIndiv",
		NTType:     13,
		Index:      18,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return functionDir.RegisterParam(X[0], X[2].(semantic.Type))
		},
	},
	ProdTabEntry{
		String: `MoreParam : comma ParamIndiv MoreParam	<<  >>`,
		Id:         "MoreParam",
		NTType:     14,
		Index:      19,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MoreParam : empty	<<  >>`,
		Id:         "MoreParam",
		NTType:     14,
		Index:      20,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Type : int	<< semantic.Int, nil >>`,
		Id:         "Type",
		NTType:     15,
		Index:      21,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return semantic.Int, nil
		},
	},
	ProdTabEntry{
		String: `Type : float	<< semantic.Float, nil >>`,
		Id:         "Type",
		NTType:     15,
		Index:      22,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return semantic.Float, nil
		},
	},
	ProdTabEntry{
		String: `Type : void	<< semantic.Void, nil >>`,
		Id:         "Type",
		NTType:     15,
		Index:      23,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return semantic.Void, nil
		},
	},
	ProdTabEntry{
		String: `Body : lbrace StateDeclare rbrace	<<  >>`,
		Id:         "Body",
		NTType:     16,
		Index:      24,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `StateDeclare : Statement StateDeclare	<<  >>`,
		Id:         "StateDeclare",
		NTType:     17,
		Index:      25,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `StateDeclare : empty	<<  >>`,
		Id:         "StateDeclare",
		NTType:     17,
		Index:      26,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Statement : Assign	<< cuadruple.AddOperatorAction(semantic.Semicolon) >>`,
		Id:         "Statement",
		NTType:     18,
		Index:      27,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.Semicolon)
		},
	},
	ProdTabEntry{
		String: `Statement : Condition	<<  >>`,
		Id:         "Statement",
		NTType:     18,
		Index:      28,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Statement : Cycle	<<  >>`,
		Id:         "Statement",
		NTType:     18,
		Index:      29,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Statement : FuncCall	<<  >>`,
		Id:         "Statement",
		NTType:     18,
		Index:      30,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Statement : Print	<<  >>`,
		Id:         "Statement",
		NTType:     18,
		Index:      31,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Assign : Id_Assign Add_Assign Expresion semicolon	<<  >>`,
		Id:         "Assign",
		NTType:     19,
		Index:      32,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Add_Assign : assign	<< cuadruple.AddOperatorAction(semantic.Assign) >>`,
		Id:         "Add_Assign",
		NTType:     20,
		Index:      33,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.Assign)
		},
	},
	ProdTabEntry{
		String: `Id_Assign : id	<< cuadruple.AddVariableAction(X[0]) >>`,
		Id:         "Id_Assign",
		NTType:     21,
		Index:      34,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddVariableAction(X[0])
		},
	},
	ProdTabEntry{
		String: `Condition : If_Begin lparen Expresion rparen If_Body ElseBody semicolon	<<  >>`,
		Id:         "Condition",
		NTType:     22,
		Index:      35,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `If_Begin : if	<< cuadruple.AddBeginIfAction() >>`,
		Id:         "If_Begin",
		NTType:     23,
		Index:      36,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddBeginIfAction()
		},
	},
	ProdTabEntry{
		String: `If_Body : Body	<< cuadruple.CompleteIfAction() >>`,
		Id:         "If_Body",
		NTType:     24,
		Index:      37,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.CompleteIfAction()
		},
	},
	ProdTabEntry{
		String: `ElseBody : Else_Begin Body	<<  >>`,
		Id:         "ElseBody",
		NTType:     25,
		Index:      38,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ElseBody : empty	<<  >>`,
		Id:         "ElseBody",
		NTType:     25,
		Index:      39,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Else_Begin : else	<<  >>`,
		Id:         "Else_Begin",
		NTType:     26,
		Index:      40,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Cycle : while lparen Expresion rparen do Body semicolon	<<  >>`,
		Id:         "Cycle",
		NTType:     27,
		Index:      41,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FuncCall : id lparen ArgList rparen semicolon	<<  >>`,
		Id:         "FuncCall",
		NTType:     28,
		Index:      42,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ArgList : Expresion MoreCall	<<  >>`,
		Id:         "ArgList",
		NTType:     29,
		Index:      43,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ArgList : empty	<<  >>`,
		Id:         "ArgList",
		NTType:     29,
		Index:      44,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `MoreCall : comma Expresion MoreCall	<<  >>`,
		Id:         "MoreCall",
		NTType:     30,
		Index:      45,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MoreCall : empty	<<  >>`,
		Id:         "MoreCall",
		NTType:     30,
		Index:      46,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Print : print lparen PrintList rparen semicolon	<<  >>`,
		Id:         "Print",
		NTType:     31,
		Index:      47,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `PrintList : PrintItem MorePrint	<<  >>`,
		Id:         "PrintList",
		NTType:     32,
		Index:      48,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `PrintItem : Expresion	<<  >>`,
		Id:         "PrintItem",
		NTType:     33,
		Index:      49,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `PrintItem : cte_string	<<  >>`,
		Id:         "PrintItem",
		NTType:     33,
		Index:      50,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MorePrint : comma PrintItem MorePrint	<<  >>`,
		Id:         "MorePrint",
		NTType:     34,
		Index:      51,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MorePrint : empty	<<  >>`,
		Id:         "MorePrint",
		NTType:     34,
		Index:      52,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Expresion : Exp MoreExpresion	<<  >>`,
		Id:         "Expresion",
		NTType:     35,
		Index:      53,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Exp : Termino MoreExp	<<  >>`,
		Id:         "Exp",
		NTType:     36,
		Index:      54,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Termino : Factor MoreTermino	<<  >>`,
		Id:         "Termino",
		NTType:     37,
		Index:      55,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Factor : Agregar_Paren Expresion Terminar_Paren	<<  >>`,
		Id:         "Factor",
		NTType:     38,
		Index:      56,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Factor : Plus_Minus id	<< cuadruple.AddVariableAction(X[0]) >>`,
		Id:         "Factor",
		NTType:     38,
		Index:      57,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddVariableAction(X[0])
		},
	},
	ProdTabEntry{
		String: `Factor : Plus_Minus Cte	<<  >>`,
		Id:         "Factor",
		NTType:     38,
		Index:      58,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Factor : id	<< cuadruple.AddVariableAction(X[0]) >>`,
		Id:         "Factor",
		NTType:     38,
		Index:      59,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddVariableAction(X[0])
		},
	},
	ProdTabEntry{
		String: `Factor : Cte	<<  >>`,
		Id:         "Factor",
		NTType:     38,
		Index:      60,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Agregar_Paren : lparen	<< cuadruple.AddOperatorAction(semantic.NewPara) >>`,
		Id:         "Agregar_Paren",
		NTType:     39,
		Index:      61,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.NewPara)
		},
	},
	ProdTabEntry{
		String: `Terminar_Paren : rparen	<< cuadruple.AddOperatorAction(semantic.ClosePara) >>`,
		Id:         "Terminar_Paren",
		NTType:     40,
		Index:      62,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.ClosePara)
		},
	},
	ProdTabEntry{
		String: `MoreExpresion : Greater_Less_NotEqual Exp	<<  >>`,
		Id:         "MoreExpresion",
		NTType:     41,
		Index:      63,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MoreExpresion : empty	<<  >>`,
		Id:         "MoreExpresion",
		NTType:     41,
		Index:      64,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Greater_Less_NotEqual : greater	<< cuadruple.AddOperatorAction(semantic.Greater) >>`,
		Id:         "Greater_Less_NotEqual",
		NTType:     42,
		Index:      65,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.Greater)
		},
	},
	ProdTabEntry{
		String: `Greater_Less_NotEqual : less	<< cuadruple.AddOperatorAction(semantic.Less) >>`,
		Id:         "Greater_Less_NotEqual",
		NTType:     42,
		Index:      66,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.Less)
		},
	},
	ProdTabEntry{
		String: `Greater_Less_NotEqual : notequal	<< cuadruple.AddOperatorAction(semantic.NotEqual) >>`,
		Id:         "Greater_Less_NotEqual",
		NTType:     42,
		Index:      67,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.NotEqual)
		},
	},
	ProdTabEntry{
		String: `MoreExp : Plus_Minus Termino	<<  >>`,
		Id:         "MoreExp",
		NTType:     43,
		Index:      68,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MoreExp : empty	<<  >>`,
		Id:         "MoreExp",
		NTType:     43,
		Index:      69,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Plus_Minus : plus	<< cuadruple.AddOperatorAction(semantic.Plus) >>`,
		Id:         "Plus_Minus",
		NTType:     44,
		Index:      70,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.Plus)
		},
	},
	ProdTabEntry{
		String: `Plus_Minus : minus	<< cuadruple.AddOperatorAction(semantic.Minus) >>`,
		Id:         "Plus_Minus",
		NTType:     44,
		Index:      71,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.Minus)
		},
	},
	ProdTabEntry{
		String: `MoreTermino : Times_Div Factor	<<  >>`,
		Id:         "MoreTermino",
		NTType:     45,
		Index:      72,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MoreTermino : empty	<<  >>`,
		Id:         "MoreTermino",
		NTType:     45,
		Index:      73,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Times_Div : times	<< cuadruple.AddOperatorAction(semantic.Times) >>`,
		Id:         "Times_Div",
		NTType:     46,
		Index:      74,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.Times)
		},
	},
	ProdTabEntry{
		String: `Times_Div : divide	<< cuadruple.AddOperatorAction(semantic.Divide) >>`,
		Id:         "Times_Div",
		NTType:     46,
		Index:      75,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return cuadruple.AddOperatorAction(semantic.Divide)
		},
	},
	ProdTabEntry{
		String: `Cte : cte_int	<< semantic.Int, nil >>`,
		Id:         "Cte",
		NTType:     47,
		Index:      76,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return semantic.Int, nil
		},
	},
	ProdTabEntry{
		String: `Cte : cte_float	<< semantic.Float, nil >>`,
		Id:         "Cte",
		NTType:     47,
		Index:      77,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib, C interface{}) (Attrib, error) {
			return semantic.Float, nil
		},
	},
}
