// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"babyduck/token"
)

const (
	NoState    = -1
	NumStates  = 71
	NumSymbols = 91
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: 'p'
1: 'r'
2: 'o'
3: 'g'
4: 'r'
5: 'a'
6: 'm'
7: 'm'
8: 'a'
9: 'i'
10: 'n'
11: 'v'
12: 'a'
13: 'r'
14: 'e'
15: 'n'
16: 'd'
17: 'i'
18: 'n'
19: 't'
20: 'f'
21: 'l'
22: 'o'
23: 'a'
24: 't'
25: 'v'
26: 'o'
27: 'i'
28: 'd'
29: 'w'
30: 'h'
31: 'i'
32: 'l'
33: 'e'
34: 'd'
35: 'o'
36: 'p'
37: 'r'
38: 'i'
39: 'n'
40: 't'
41: 'i'
42: 'f'
43: 'e'
44: 'l'
45: 's'
46: 'e'
47: ';'
48: ':'
49: ','
50: '{'
51: '}'
52: '('
53: ')'
54: '['
55: ']'
56: '='
57: '+'
58: '-'
59: '>'
60: '<'
61: '!'
62: '='
63: '*'
64: '/'
65: '_'
66: '.'
67: '"'
68: '"'
69: ' '
70: '\t'
71: '\n'
72: '\r'
73: 'a'-'z'
74: 'a'-'z'
75: 'A'-'Z'
76: 'a'-'z'
77: 'A'-'Z'
78: '0'-'9'
79: 'a'-'z'
80: 'A'-'Z'
81: '0'-'9'
82: '0'-'9'
83: '0'-'9'
84: '0'-'9'
85: '0'-'9'
86: '0'-'9'
87: '0'-'9'
88: 'a'-'z'
89: 'A'-'Z'
90: .
*/
