// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"babyduck/token"
)

const (
	NoState    = -1
	NumStates  = 73
	NumSymbols = 84
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: 'p'
1: 'r'
2: 'o'
3: 'g'
4: 'r'
5: 'a'
6: 'm'
7: 'm'
8: 'a'
9: 'i'
10: 'n'
11: 'e'
12: 'n'
13: 'd'
14: 'v'
15: 'a'
16: 'r'
17: 'v'
18: 'o'
19: 'i'
20: 'd'
21: 'i'
22: 'n'
23: 't'
24: 'f'
25: 'l'
26: 'o'
27: 'a'
28: 't'
29: 'i'
30: 'f'
31: 'e'
32: 'l'
33: 's'
34: 'e'
35: 'w'
36: 'h'
37: 'i'
38: 'l'
39: 'e'
40: 'd'
41: 'o'
42: 'p'
43: 'r'
44: 'i'
45: 'n'
46: 't'
47: '='
48: '!'
49: '='
50: '<'
51: '>'
52: '+'
53: '-'
54: '*'
55: '/'
56: ':'
57: ';'
58: ','
59: '('
60: ')'
61: '{'
62: '}'
63: '['
64: ']'
65: '0'
66: '0'
67: '.'
68: '"'
69: ' '
70: '!'
71: '?'
72: '"'
73: '_'
74: '\t'
75: '\n'
76: '\r'
77: ' '
78: '1'-'9'
79: '1'-'9'
80: 'a'-'z'
81: 'A'-'Z'
82: '0'-'9'
83: .
*/
